/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fks.ui.constants;

/**
 *
 * @author ajitn
 */
public enum PropertyEnum {

    PROPOSAL_ARTICLE_FILE_PATH,
    PROPOSAL_OTHER_FILE_PATH,
    COMMON_DIRECTORY_PATH,
    INITIATE_ARTICLE_FILE_PATH,
    TASK_FILE_PATH,
    SUB_PROMOTION_FILE_PATH,
    LSMW_FILE,
    SUB_PROMOTION_TEMPLATE_FILE_PATH,
    PROMO_CLOSE,
    SAP_WEB_UI,
    SITE_UPLOAD_TEMPLATE_FILE_PATH,
    CHANGE_DATE_FILE_PATH,    
    CHANGE_MC_ARTICLE_PATH,
    CHANGE_STORE_DETAIL_PATH,
    MC_WISE_LEAD_TIME_PATH,
    INTEGRATED_TIC_REQ_NO,
    INTEGRATED_PROMO_STORE,
    INTEGRATED_MC_DETAILS,
    INTEGRATED_ARTICLE_DETAILS,
    LSMW_SITE_UPLOAD_TEMPLATE_FILE_PATH,
    CHANGE_LSMW_SITE_UPLOAD_FILE_PATH,
    VISTEX_MASTER_UPLOAD_TEMPLATE_FILE_PATH,
    VISTEX_MASTER_TEMPLATE_SAMPLE_FILE_PATH,
    DUPLICATE_REQUEST_FILE,
    TRANS_PROMO_MODIFICATION_UPLOAD_FILE_PATH,
    // Added by Dhaval Promotion Modification
    MODIFY_CHANGE_DATE_FILE_PATH,
    MODIFY_ADD_MC_ARTICLE_PATH,
    MODIFY_REMOVE_MC_ARTICLE_PATH,
    // Added End 
    
    //Added By Marichi for PWM 698 -- Start
    PROMO_INVISIBLE,
    PROMO_INVISIBLE_TEMPLATE
    //Added By Marichi for PWM 698 -- End
}
